#!/bin/bash

#comment or uncomment the appropriate set of lines to run hexplit on the set of files you want to run hexplit on

#particle=gamma
particle=neutron
dir=cache/${particle}_zdc_inf/
mkdir $dir

for E in 10 20 50 100 200 275; do
     #zdc_s1_inf zdc_s2_inf zdc_staggered_h3_inf zdc_staggered_h4_inf zdc_unstaggered_inf; do
    python3 process_showers.py  ${dir}/zdc_staggered_h3_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root ${dir}/zdc_staggered_h3_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root.csv --w0_use_range --H3 &
    python3 process_showers.py ${dir}/zdc_staggered_h4_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root ${dir}/zdc_staggered_h4_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root.csv --w0_use_range --H4 &
    python3 process_showers.py ${dir}/zdc_unstaggered_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root ${dir}/zdc_unstaggered_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root.csv --w0_use_range &
    #python3 process_showers.py ${dir}/zdc_s1_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root ${dir}/zdc_s1_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root.csv --w0_use_range &
    #python3 process_showers.py ${dir}/zdc_s2_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root ${dir}/zdc_s2_inf_reco_${particle}_${E}GeV_theta_deg.edm4hep.root.csv --w0_use_range --S2 &
    
done

wait
