#!/bin/bash

run_sim () {
# Input simulation parameters
particle="neutron"
beam_energy=$1
num_events=2000
theta_min=0.0 # in degrees
theta_max=0.5 # in degrees
phi_min=0. # in degrees
phi_max=360. # in degrees 
physics_list="FTFP_BERT_HP"
config=$2

# Output file names
info_string="${particle}_${beam_energy}GeV_theta_${theta}deg"
hepmcfile="gen_${info_string}.hepmc"
simfile="${config}_sim_${info_string}.edm4hep.root"
recofile="${config}_reco_${info_string}.edm4hep.root"

# Generating hepmc file
root -l -b -q "./hepmc_generation/gen_particles.cxx+(\
${num_events},\
\"${hepmcfile}\",\
\"${particle}\",\
${theta_min},\
${theta_max},\
${phi_min},\
${phi_max},\
${beam_energy})"

# Running simulation
npsim \
   --compactFile ${config}.xml \
   --numberOfEvents ${num_events} \
   --physicsList ${physics_list} \
   --inputFiles ${hepmcfile} \
   --outputFile ${simfile}  || exit
   
# Deleting hepmcfile  
rm ${hepmcfile}

# Running reconstruction
export JUGGLER_SIM_FILE=${simfile} JUGGLER_REC_FILE=${recofile} JUGGLER_N_EVENTS=${num_events} JUGGLER_DETECTOR_NAME=${config}
gaudirun.py zdc_reco.py
}

for E in 10 20 50 100 200 275; do
    for geom in zdc_s1_inf zdc_s2_inf zdc_staggered_h3_inf zdc_staggered_h4_inf zdc_unstaggered_inf; do
	run_sim	$E $geom &
    done
done

wait
